### ISSUE TITLE
Package 'python3-crypto' has no installation candidate

### ISSUE THREAD

**Issue by ramonp1979** [Jerrythafast/se-logger#11]
I'm having some trouble to migrate se-logger to a new Debian version.
It is working fine on Debian 9.13 (stretch)
With python 2.7.13 
Se-logger version is 0.10

My new Debian version is 11 (bullseye)
With Python 3.9.2
And se-logger version 0.17 (the latest)

The problem is that the package 'python3-crypto' does not exist anymore.

Package python3-crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-crypto' has no installation candidate

Do you have a solution for this?

**Comment by Jerrythafast** [comment]
You could try installing `pycryptodome`, it should be compatible. Run this to install it:
`python3 -m pip install pycryptodome`

**Comment by ramonp1979** [comment]
That is not working. Here is the content of the liveupdate.log:

Traceback (most recent call last):
  File "/opt/se-logger/liveupdate.py", line 503, in <module>
    parser = SEParser(inverter_private_key, decryptor=SEDecrypt(inverter_private
_key, last_0503), msg_filt=set((0x0500, 0x0503)))
  File "/opt/se-logger/liveupdate.py", line 117, in __init__
    enkey1 = AES.new(key, mode=AES.MODE_ECB).encrypt(bytes(msg0503[0:16]))
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Cipher/AES.py", line 228,
in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Cipher/__init__.py", line
79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Cipher/_mode_ecb.py", line
 216, in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Cipher/AES.py", line 100,
in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Util/_raw_api.py", line 24
2, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by Jerrythafast** [comment]
Hmm I see, not perfectly compatible it seems. My best bet would be that one small thing needs to be chagend on [line 117 of liveupdate.py](https://github.com/Jerrythafast/se-logger/blob/1426f17d22d889d07a026a68a5753dd9e5f40c53/opt/se-logger/liveupdate.py#L117): the `key` parameter probably needs to be changed to `bytes(key)`. Could you give that a try?

**Comment by ramonp1979** [comment]
I changed line 117 from:
enkey1 = AES.new(**key**, mode=AES.MODE_ECB).encrypt(bytes(msg0503[0:16]))
to
enkey1 = AES.new(**bytes(key)**, mode=AES.MODE_ECB).encrypt(bytes(msg0503[0:16]))

This is the result in the liveupdate.log:

Traceback (most recent call last):
  File "/opt/se-logger/liveupdate.py", line 504, in <module>
    parser = SEParser(inverter_private_key, decryptor=SEDecrypt(inverter_private_key, last_0503), msg_filt=set((0x0500, 0x0
503)))
  File "/opt/se-logger/liveupdate.py", line 118, in __init__
    enkey1 = AES.new(bytes(key), mode=AES.MODE_ECB).encrypt(bytes(msg0503[0:16]))
TypeError: string argument without an encoding

**Comment by Jerrythafast** [comment]
Oh heh silly me, if it's a `str` the encoding must be given.
But this got me thinking: this is not the solution, it doesn't make sense for the `key` to be a `str` in the first place.

The root cause of the issues probably lies in the `inverter_private_key` config variable. Its value should be a *bytes literal*, i.e. there should be a `b` before the opening quote. See [config-sample.py](https://github.com/Jerrythafast/se-logger/blob/1426f17d22d889d07a026a68a5753dd9e5f40c53/opt/se-logger/config-sample.py) for an example that should work.

**Comment by ramonp1979** [comment]
That is the solution.
I just copied the entire line from the old version (with out the b) to the new configuration file.
I didn't noticed the difference.

Thanks

**Comment by Jerrythafast** [comment]
Perfect! I'll leave this issue open as a reminder to update the readme regarding the crypto library. And maybe I can add a type check to the key argument to give a helpful message for others migrating from python2. Thanks for reporting and trying my suggestions!

**Comment by RWSahi** [comment]
@ramonp1979 
Just ran into question.
In the past i had Jerry his system running on a RPI 1
I want to use it agian, but what php, mysql  versions are you using on Debian 11?

**Comment by ramonp1979** [comment]
> [@ramonp1979](https://github.com/ramonp1979) Just ran into question. In the past i had Jerry his system running on a RPI 1 I want to use it agian, but what php, mysql versions are you using on Debian 11?

PHP is version 8.3.16
MariaDB is version 10.11
